language: go

go:
  - 1.7
  - 1.8

install:
  - make install

before_script:
  - PKGS=$(go list ./... | grep -v /vendor/ )
  - go get -v honnef.co/go/tools/cmd/{gosimple,staticcheck}

script:
  - make test-v
  - make test-vendor-v
  - go vet $PKGS
  - staticcheck $PKGS
  - gosimple $PKGS
