language: go

go:
  - 1.7
  - 1.8

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - make install

before_script:
  - PKGS=$(go list ./... | grep -v /vendor/ )
  - go get -v honnef.co/go/tools/cmd/{gosimple,staticcheck}

script:
  - make test
  - make test-vendor
  - go vet $PKGS
  - staticcheck $PKGS
  - gosimple $PKGS
